apiVersion: v2
name: cnpg-cluster
description: Helm chart for CloudNativePG cluster managment.
type: application
version: 0.1.0
appVersion: "1.28.1"
keywords:
  - postgresql
  - cnpg
  - cloudnative-pg
  - database
  - external-secrets
  - vault
