global:
  vaultSecretPath: ""
  secretStoreName: ""

cluster:
  name: ""
  instances: ""
  storageSize: ""
  monitoring: {}
  bootstrap: {}

databases: []
#  - name: ""
#    owner: ""

users: []
#  - name: ""
#    superuser: false
#    connectionLimit: 20
#    vaultPath: ""
#    inRoles: []
