apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.cluster.name }}
spec:
  instances: {{ .Values.cluster.instances }}
  
  storage:
    size: {{ .Values.cluster.storageSize }}

  managed:
    roles:
      {{- range .Values.users }}
      - name: {{ .name }}
        ensure: {{ .ensure | default "present" }}
        login: true
        superuser: {{ .superuser | default false }}
        inherit: true
        connectionLimit: {{ .connectionLimit | default 20 }}
        passwordSecret:
          name: pguser-{{ .name }}
        {{- if .inRoles }}
        inRoles:
          {{- toYaml .inRoles | nindent 10 }}
        {{- end }}
      {{- end }}

  # Conditional Bootstrap section
  {{- if .Values.cluster.bootstrap.enabled }}
  bootstrap:
    initdb:
      {{- with .Values.cluster.bootstrap.initdb }}
      database: {{ .database | quote }}
      owner: {{ .owner | quote }}
      {{- if .secret }}
      # Optional: if you want to use a specific secret for the app user
      secret:
        name: {{ .secret }}
      {{- end }}
      {{- end }}
  {{- end }}
