apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.cluster.name }}
spec:
  instances: {{ .Values.cluster.instances }}
  
  storage:
    size: {{ .Values.cluster.storageSize }}

  managed:
    roles:
      {{- range .Values.users }}
      - name: {{ .name }}
        ensure: present
        login: true
        superuser: {{ .superuser | default false }}
        inherit: true
        connectionLimit: {{ .connectionLimit | default 20 }}
        passwordSecret:
          name: psql-{{ .name }}
        {{- if .inRoles }}
        inRoles:
          {{- toYaml .inRoles | nindent 10 }}
        {{- end }}
      {{- end }}

  # Настройки мониторинга или бэкапов можно вынести сюда
  bootstrap:
    initdb:
      database: app_db
      owner: dbadmin2048
