{{- range .Values.databases }}
{{- /* Set owner to .owner if defined, otherwise fallback to .name */ -}}
{{- $dbOwner := .owner | default .name -}}
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: {{ .name }}
spec:
  cluster:
    name: {{ $.Values.cluster.name }}
  name: {{ .name }}
  owner: {{ $dbOwner }}
  ensure: present
---
{{- end }}
