{{- range .Values.users }}
{{- $userName := .name -}}

{{- /* Determine the SecretStore name: 
  Prioritize user-specific .secretStoreName, fallback to global.secretStoreName 
*/ -}}
{{- $storeName := .secretStoreName | default $.Values.global.secretStoreName -}}

{{- /* Determine the Vault path: 
  1. Use .vaultPath if explicitly defined for the user.
  2. Otherwise, construct it using global.vaultSecretPath and the username. 
*/ -}}
{{- $finalPath := .vaultPath | default (printf "%s/%s" $.Values.global.vaultSecretPath $userName) -}}

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: psql-{{ $userName }}
  labels:
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
spec:
  refreshInterval: "30s"
  secretStoreRef:
    name: {{ $storeName }}
    kind: ClusterSecretStore
  target:
    name: psql-{{ $userName }}
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          # This label triggers CNPG to reload the secret when it changes in Vault
          cnpg.io/reload: "true"
  data:
    - secretKey: username
      remoteRef:
        key: {{ $finalPath }}
        property: username
    - secretKey: password
      remoteRef:
        key: {{ $finalPath }}
        property: password
---
{{- end }}
