{{- range .Values.users }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: psql-{{ .name }}
spec:
  refreshInterval: "30s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: psql-{{ .name }}
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: username
      remoteRef:
        key: {{ .vaultPath }}
        property: username
    - secretKey: password
      remoteRef:
        key: {{ .vaultPath }}
        property: password
---
{{- end }}
